# Generated by Django 3.0.8 on 2020-08-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_resource_submission_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='filename',
            field=models.CharField(default='filename', max_length=128),
        ),
    ]
