# Generated by Django 3.0.8 on 2020-08-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='lms.Subject'),
        ),
    ]
