# Generated by Django 3.0.8 on 2020-08-07 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='doc',
            field=models.FileField(null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='filename',
            field=models.CharField(default='filename-student', max_length=128),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=1028, verbose_name='Post Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=64, verbose_name='Post Title'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('title', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Assignment'),
        ),
    ]
