# Generated by Django 3.0.8 on 2020-08-07 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_auto_20200807_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='homework',
            new_name='assignment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.Subject'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='title', max_length=128),
        ),
    ]
