# Generated by Django 3.0.8 on 2020-08-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_auto_20200807_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='Assignment', max_length=128),
        ),
        migrations.AlterField(
            model_name='resource',
            name='doc',
            field=models.FileField(upload_to='resources/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(default='chemistry', on_delete=django.db.models.deletion.CASCADE, to='lms.Subject', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='doc',
            field=models.FileField(null=True, upload_to='submissions/', verbose_name=''),
        ),
    ]
