# Generated by Django 3.0.8 on 2020-08-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_auto_20200809_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.CharField(default='', max_length=256, verbose_name='Lesson URL (YouTube)'),
        ),
        migrations.AddField(
            model_name='user',
            name='notifs',
            field=models.ManyToManyField(blank=True, related_name='notif', to='lms.Notification'),
        ),
    ]
