# Generated by Django 3.0.8 on 2020-08-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_auto_20200809_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='name',
            new_name='text',
        ),
    ]
